### ISSUE TITLE
Location of ExTASY 0.2 examples

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#192]
In ExTASY 0.2, we have moved from providing a pre-canned 'extasy' executable that only knows about w workflows, to providing an API, with which you can construct your own.  The documentation on http://extasy.readthedocs.org/en/extasy_0.2/index.html explains how to run example workflows, and the supporting tar files are in git.  I think to make the code more user-friendly for potential developers we should restructure the 'tarballs' directory:

* rename it to 'examples' since that's what it contains.
* If we need to keep the tarballs in git fine, but put them somewhere else, no-one needs them except via the download links in the tutorial
* Inside 'examples' have:
examples/coco-amber
and
example/gromacs-lsdmap
* Each directory should contain the relevant script (e.g. extasy_amber_coco.py), the .wcfg file and example .rcfg files for ARCHER and Stampede.
* The inp_files directory is fine to keep all the input files in, that makes sense
* What is misc files for, can it be deleted?

I hope this should make it much clearer for people to understand what it is we are offering them, esp. if they choose not to follow the tutorial steps.

**Comment by vivek-bala** [comment]
The wcfg files are currently bound to the machine. In the sense, for ARCHER the number of CUs is 24 (since min number of cores we can get is 24) and similarily 16 for Stampede. I see 3 options:

1) 
examples/coco-amber/stampede/...
examples/coco-amber/archer/...
examples/gromacs-lsdmap/stampede/...
examples/gromacs-lsdmap/archer/...

This is the current hierarchy.

2)
examples/coco-amber/stampede.rcfg
examples/coco-amber/archer.rcfg
examples/coco-amber/cocoamber_on_stampede.wcfg
examples/coco-amber/cocoamber_on_archer.wcfg

examples/gromacs-lsdmap/stampede.rcfg
examples/gromacs-lsdmap/archer.rcfg
examples/gromacs-lsdmap/gromacslsdmap_on_stampede.wcfg
examples/gromacs-lsdmap/gromacslsdmap_on_archer.wcfg

3) Have a common .wcfg for both stampede and archer. Set num of CUs as min(Stampede cores,Archer cores).

Open to all 3. Option 2 might be easier to understand for the users (?)

**Comment by vivek-bala** [comment]
The misc_files folder contains scripts which perform splitting up the input files (gromacs), selection+reweighting (lsdmap), tleap(amber), etc. Probably can be moved into inp_files.

**Comment by ibethune** [comment]
I think number 2 is the best option.  misc_files I think should be separate since these are part of the implementation of the workflow, rather than the input files to the workflow - if someone wanted to swap in a different system, they wouldn't need to edit them.  How about calling them 'helper_scripts' ?

**Comment by vivek-bala** [comment]
Agreed
