### ISSUE TITLE
ExTASY 0.2 - support for pyCoCo -s option?

### ISSUE THREAD

**Issue by CharlieLaughton** [radical-cybertools/ExTASY#195]
Does the ExTASY-0.2 version of the CoCo-Amber workflow support the pyCoCo "-s" or equivalent  "--selection" option yet? This allows a selected subset of atoms from the trajectory file (e.g. just the solute, not the solvent) to be used for the CoCo process. I can't see this documented in the example cocoamber.wcfg file (though for the penta-alanine example it's not needed, so maybe that's why), but I can't see it in the python scripts either. We need it implemented for the CECAM workshop.

**Comment by vivek-bala** [comment]
There were some issues with coco 0.19 that had come up. I had reported them to Ardita but apologies for not cc'ing the group.

1) All fails with '--selection' parameter failed because of a reshaping error.
2) Using the '--mpi' parameter with multiple cores failed, because multiple threads tried to create the pdb folder.

Currently, both 0.1 and 0.2, coco 0.19 is executed without the '--selection' parameter and on 1 core.

Once coco is stable for the 2 issues, adding the support for the --selection' parameter is trivial.

**Comment by ashkurti** [comment]
Please note, that this issues have now been fixed at the new version of coco-0.21 that is now installed on stampede and publicly available at /work/02998/ardi/coco-0.21_installation.

**Comment by vivek-bala** [comment]
This is now available both in 0.1 and 0.2.
