### ISSUE TITLE
ExTASY 0.2 grompp not recognised on Stampede

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#207]
While finalizing the tests of the extasy_gmxcoco workflow on Stampede, today I have an error message complaining that grompp is not recognized on stampede - I did not have any such errors last week.

In particular, at folder /work/02998/ardi/radical.pilot.sandbox/rp.session.moriarty.pharm.nottingham.ac.uk.ardita.016727.0002-pilot.0000/unit.000012/ have a look at STDERR and at radical_pilot_cu_launch_script.sh

I have executed the script locally at the same folder submitting it in the queue and it did not show any such errors but grompp was recognized instead.

ExTASY log at: https://gist.github.com/ashkurti/9f31a8463bb6dee02195

Could anyone please give a look at this and advise.

**Comment by vivek-bala** [comment]
The changed the modules on stampede again. Sigh. Removing cxx11 should work.

**Comment by ashkurti** [comment]
I removed it from all three kernels, but it presented the same problem, grompp not found :(

As said previously, executing the script of which it complains on stampede would not issue these errors, no problems even if the script contains the cxx11 module.

**Comment by vivek-bala** [comment]
Hi Ardita, 

"cxx11" is required with intel/15* which we are using. 

But the error seems to be while using 0.37.2. I have created a ticket: https://github.com/radical-cybertools/radical.pilot/issues/854. Since all of our examples are tested with 0.37, I can force ensemblemd to install 0.37 and not 0.37.*. But I would like to confirm this with RP team first, incase we will be missing out on any essential features.

**Comment by ashkurti** [comment]
Thanks for investigating on this Vivek.

**Comment by ashkurti** [comment]
I checked this after noticing that @marksantcroos closed issue radical-cybertools/radical.pilot#854
Now things are working for me. Thanks @vivek-bala and @marksantcroos !!
